package com.konsol.beatstream.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArtistAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArtistAllPropertiesEquals(Artist expected, Artist actual) {
        assertArtistAutoGeneratedPropertiesEquals(expected, actual);
        assertArtistAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArtistAllUpdatablePropertiesEquals(Artist expected, Artist actual) {
        assertArtistUpdatableFieldsEquals(expected, actual);
        assertArtistUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArtistAutoGeneratedPropertiesEquals(Artist expected, Artist actual) {
        assertThat(expected)
            .as("Verify Artist auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArtistUpdatableFieldsEquals(Artist expected, Artist actual) {
        assertThat(expected)
            .as("Verify Artist relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getBio()).as("check bio").isEqualTo(actual.getBio()))
            .satisfies(e -> assertThat(e.getCoverImageFileId()).as("check coverImageFileId").isEqualTo(actual.getCoverImageFileId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArtistUpdatableRelationshipsEquals(Artist expected, Artist actual) {
        // empty method
    }
}
